service: esm-azure-sls

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

functions:
  whatday:
    handler: handler.whatday
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
